from __future__ import unicode_literals
import frappe

def execute():
	create_form_tour_fields()
	create_form_tour_steps_fields()

def create_form_tour_fields():

	doc_ = frappe.new_doc("Custom Field")
	doc_.dt = "Form Tour"
	doc_.label = "Module"
	doc_.fieldname = "module"
	doc_.insert_after = ""
	doc_.fieldtype = "Link"
	doc_.options="Module Def"
	doc_.fetch_from= "reference_doctype.module"
	doc_.hidden=0
	doc_.read_only=1
	doc_.save(ignore_permissions=True)

	doc = frappe.new_doc("Custom Field")
	doc.dt = "Form Tour"
	doc.label = "Is Standard"
	doc.fieldname = "is_standard"
	doc.insert_after = "module"
	doc.fieldtype = "Check"
	doc.default=0
	doc.save(ignore_permissions=True)

def create_form_tour_steps_fields():

	custom_field=[{
	'dt': 'Form Tour Step',
	'label': 'Is Table Field',
	'fieldname': 'is_table_field',
	'insert_after': 'field',
	'length': 0,
	'fieldtype': 'Check',
	'options': None,
	'fetch_from': None,
	'fetch_if_empty': 0,
	'collapsible': 0,
	'collapsible_depends_on': None,
	'default': '0',
	'depends_on': None,
	'mandatory_depends_on': None,
	'read_only_depends_on': None,
	'non_negative': 0,
	'reqd': 0,
	'unique': 0,
	'read_only': 0,
	'ignore_user_permissions': 0,
	'hidden': 0,
	'print_hide': 0,
	'print_hide_if_no_value': 0,
	'print_width': None,
	'no_copy': 0,
	'allow_on_submit': 0,
	'in_list_view': 0,
	'in_standard_filter': 0,
	'in_global_search': 0,
	'in_preview': 0,
	'bold': 0,
	'report_hide': 0,
	'search_index': 0,
	'allow_in_quick_entry': 0,
	},
	{

	'dt': 'Form Tour Step',
	'label': None,
	'fieldname': 'section_break_2',
	'insert_after': 'is_table_field',
	'length': 0,
	'fieldtype': 'Section Break',
	'precision': '',
	'hide_seconds': 0,
	'hide_days': 0,
	'options': None,
	'fetch_from': None,
	'fetch_if_empty': 0,
	'collapsible': 0,
	'collapsible_depends_on': None,
	'default': None,
	'depends_on': None,
	'mandatory_depends_on': None,
	'read_only_depends_on': None,
	'non_negative': 0,
	'reqd': 0,
	'unique': 0,
	'read_only': 0,
	'ignore_user_permissions': 0,
	'hidden': 0,
	'print_hide': 0,
	'print_hide_if_no_value': 0,
	'print_width': None,
	'no_copy': 0,
	'allow_on_submit': 0,
	'in_list_view': 0,
	'in_standard_filter': 0,
	'in_global_search': 0,
	'in_preview': 0,
	'bold': 0,
	'report_hide': 0,
	'search_index': 0,
	'allow_in_quick_entry': 0,
	},
	{
	
	'dt': 'Form Tour Step',
	'label': 'Parent Field',
	'fieldname': 'parent_fieldname',
	'insert_after': 'section_break_2',
	'length': 0,
	'fieldtype': 'Select',
	'precision': '',
	'hide_seconds': 0,
	'hide_days': 0,
	'options': None,
	'fetch_from': None,
	'fetch_if_empty': 0,
	'collapsible': 0,
	'collapsible_depends_on': None,
	'default': None,
	'depends_on': 'is_table_field',
	'mandatory_depends_on': 'is_table_field',
	'read_only_depends_on': None,
	'non_negative': 0,
	'reqd': 0,
	'unique': 0,
	'read_only': 0,
	'ignore_user_permissions': 0,
	'hidden': 0,
	'print_hide': 0,
	'print_hide_if_no_value': 0,
	'print_width': None,
	'no_copy': 0,
	'allow_on_submit': 0,
	'in_list_view': 0,
	'in_standard_filter': 0,
	'in_global_search': 0,
	'in_preview': 0,
	'bold': 0,
	'report_hide': 0,
	'search_index': 0,
	'allow_in_quick_entry': 0,
	'ignore_xss_filter': 0,
	'translatable': 1,
	'hide_border': 0,
	'description': None,
	'permlevel': 0,
	'width': None,
	'columns': 0,
	'_user_tags': None,
	'_comments': None,
	'_assign': None,
	'_liked_by': None},
	{

	'dt': 'Form Tour Step',
	'label': 'Fieldtype',
	'fieldname': 'fieldtype',
	'insert_after': 'label',
	'length': 0,
	'fieldtype': 'Data',
	'precision': '',
	'hide_seconds': 0,
	'hide_days': 0,
	'options': None,
	'fetch_from': None,
	'fetch_if_empty': 0,
	'collapsible': 0,
	'collapsible_depends_on': None,
	'default': None,
	'depends_on': None,
	'mandatory_depends_on': None,
	'read_only_depends_on': None,
	'non_negative': 0,
	'reqd': 0,
	'unique': 0,
	'read_only': 1,
	'ignore_user_permissions': 0,
	'hidden': 0,
	'print_hide': 0,
	'print_hide_if_no_value': 0,
	'print_width': None,
	'no_copy': 0,
	'allow_on_submit': 0,
	'in_list_view': 0,
	'in_standard_filter': 0,
	'in_global_search': 0,
	'in_preview': 0,
	'bold': 0,
	'report_hide': 0,
	'search_index': 0,
	'allow_in_quick_entry': 0,
	'ignore_xss_filter': 0,
	'translatable': 1,
	'hide_border': 0,
	'description': None,
	'permlevel': 0,
	'width': None,
	'columns': 0,
	'_user_tags': None,
	'_comments': None,
	'_assign': None,
	'_liked_by': None},
	{
	
	'dt': 'Form Tour Step',
	'label': 'Has Next Condition',
	'fieldname': 'has_next_condition',
	'insert_after': 'fieldtype',
	'length': 0,
	'fieldtype': 'Check',
	'precision': '',
	'hide_seconds': 0,
	'hide_days': 0,
	'options': None,
	'fetch_from': None,
	'fetch_if_empty': 0,
	'collapsible': 0,
	'collapsible_depends_on': None,
	'default': '0',
	'depends_on': None,
	'mandatory_depends_on': None,
	'read_only_depends_on': None,
	'non_negative': 0,
	'reqd': 0,
	'unique': 0,
	'read_only': 0,
	'ignore_user_permissions': 0,
	'hidden': 0,
	'print_hide': 0,
	'print_hide_if_no_value': 0,
	'print_width': None,
	'no_copy': 0,
	'allow_on_submit': 0,
	'in_list_view': 0,
	'in_standard_filter': 0,
	'in_global_search': 0,
	'in_preview': 0,
	'bold': 0,
	'report_hide': 0,
	'search_index': 0,
	'allow_in_quick_entry': 0,
	},
	{
	'idx': 0,
	'dt': 'Form Tour Step',
	'label': 'Hidden Fields',
	'fieldname': 'section_break_13',
	'insert_after': None,
	'length': 0,
	'fieldtype': 'Section Break',
	'precision': '',
	'hide_seconds': 0,
	'hide_days': 0,
	'options': None,
	'fetch_from': None,
	'fetch_if_empty': 0,
	'collapsible': 0,
	'collapsible_depends_on': None,
	'default': None,
	'depends_on': None,
	'mandatory_depends_on': None,
	'read_only_depends_on': None,
	'non_negative': 0,
	'reqd': 0,
	'unique': 0,
	'read_only': 0,
	'ignore_user_permissions': 0,
	'hidden': 1,
	'print_hide': 0,
	'print_hide_if_no_value': 0,
	'print_width': None,
	'no_copy': 0,
	'allow_on_submit': 0,
	'in_list_view': 0,
	'in_standard_filter': 0,
	'in_global_search': 0,
	'in_preview': 0,
	'bold': 0,
	'report_hide': 0,
	'search_index': 0,
	'allow_in_quick_entry': 0,
	},
	{
	'idx': 1,
	'dt': 'Form Tour Step',
	'label': 'Child Doctype',
	'fieldname': 'child_doctype',
	'insert_after': 'section_break_13',
	'length': 0,
	'fieldtype': 'Data',
	'precision': '',
	'hide_seconds': 0,
	'hide_days': 0,
	'options': None,
	'fetch_from': None,
	'fetch_if_empty': 0,
	'collapsible': 0,
	'collapsible_depends_on': None,
	'default': None,
	'depends_on': None,
	'mandatory_depends_on': None,
	'read_only_depends_on': None,
	'non_negative': 0,
	'reqd': 0,
	'unique': 0,
	'read_only': 1,
	'ignore_user_permissions': 0,
	'hidden': 1,
	'print_hide': 0,
	'print_hide_if_no_value': 0,
	'print_width': None,
	'no_copy': 0,
	'allow_on_submit': 0,
	'in_list_view': 0,
	'in_standard_filter': 0,
	'in_global_search': 0,
	'in_preview': 0,
	'bold': 0,
	'report_hide': 0,
	'search_index': 0,
	'allow_in_quick_entry': 0,
	}]



	property_setter=[{'doctype_or_field': 'DocField',

	'doc_type': 'Form Tour Step',
	'field_name': 'label',
	'row_name': None,
	'property': 'fetch_from',
	'property_type': 'Small Text',
	'value': '',
	'default_value': None,
	},
	{'doctype_or_field': 'DocField',
	'doc_type': 'Form Tour Step',
	'field_name': 'field',
	'row_name': None,
	'property': 'reqd',
	'property_type': 'Check',
	'value': '0',
	'default_value': None,
	},
	{'doctype_or_field': 'DocField',
	'doc_type': 'Form Tour Step',
	'field_name': 'fieldname',
	'row_name': None,
	'property': 'depends_on',
	'property_type': 'Small Text',
	'value': 'eval: (!doc.is_table_field || (doc.is_table_field && doc.parent_fieldname))',
	'default_value': None,
	},
	{'doctype_or_field': 'DocField',
	'doc_type': 'Form Tour Step',
	'field_name': 'field',
	'row_name': None,
	'property': 'hidden',
	'property_type': 'Check',
	'value': '1',
	'default_value': None,
	},
	{'doctype_or_field': 'DocField',
	'doc_type': 'Form Tour Step',
	'field_name': 'fieldname',
	'row_name': None,
	'property': 'hidden',
	'property_type': 'Check',
	'value': '0',
	'default_value': None,
	},
	{'doctype_or_field': 'DocField',
	'doc_type': 'Form Tour Step',
	'field_name': 'fieldname',
	'row_name': None,
	'property': 'reqd',
	'property_type': 'Check',
	'value': '1',
	'default_value': None,
	},
	{'doctype_or_field': 'DocField',
	'doc_type': 'Form Tour Step',
	'field_name': 'fieldname',
	'row_name': None,
	'property': 'fieldtype',
	'property_type': 'Select',
	'value': 'Select',
	'default_value': None,
	},
	{'doctype_or_field': 'DocField',
	'doc_type': 'Form Tour Step',
	'field_name': 'fieldname',
	'row_name': None,
	'property': 'read_only',
	'property_type': 'Check',
	'value': '0',
	'default_value': None,
	},
	{  'doctype_or_field': 'DocField',
	'doc_type': 'Form Tour Step',
	'field_name': 'next_step_condition',
	'row_name': None,
	'property': 'depends_on',
	'property_type': 'Small Text',
	'value': 'has_next_condition',
	'default_value': None,
	},
	{'doctype_or_field': 'DocField',
	'doc_type': 'Form Tour Step',
	'field_name': 'fieldname',
	'row_name': None,
	'property': 'fetch_from',
	'property_type': 'Small Text',
	'value': '',
	'default_value': None,
	}]

	for each in custom_field:
		doc = frappe.new_doc("Custom Field")
		doc.update(each)
		doc.save(ignore_permissions=True)

	for each in property_setter:
		doc = frappe.new_doc("Property Setter")
		doc.update(each)
		doc.save(ignore_permissions=True)

